-- `products` tablosu
CREATE TABLE IF NOT EXISTS products (
                                        product_id BIGINT NOT NULL PRIMARY KEY,
                                        product_name VARCHAR(255) NOT NULL
);

-- `baskets` tablosu
CREATE TABLE IF NOT EXISTS baskets (
                                       basket_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       created_at DATE NOT NULL,
                                       total_quantity INT NOT NULL,
                                       customer_id BIGINT NOT NULL
);

-- `basketProductUnits` tablosu
CREATE TABLE IF NOT EXISTS basketProductUnits (
                                                  basket_product_unit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                  product_name VARCHAR(255) NOT NULL,
                                                  product_price BIGINT NOT NULL,
                                                  product_quantity INT NOT NULL,
                                                  customer_id BIGINT NOT NULL,
                                                  basket_id BIGINT NOT NULL,
                                                  FOREIGN KEY (basket_id) REFERENCES baskets(basket_id)
);

-- `products` tablosuna veri ekleme
INSERT INTO products (product_id, product_name) VALUES (1, 'Ayakkabı');
INSERT INTO products (product_id, product_name) VALUES (2, 'Çanta');

-- `baskets` tablosuna veri ekleme
INSERT INTO baskets (created_at, total_quantity, customer_id)
VALUES ('2025-01-14', 2, 101);

-- `basketProductUnits` tablosuna veri ekleme
INSERT INTO basketProductUnits (product_name, product_price, product_quantity, customer_id, basket_id)
VALUES ('Ayakkabı', 200, 1, 101, 1);

INSERT INTO basketProductUnits (product_name, product_price, product_quantity, customer_id, basket_id)
VALUES ('Çanta', 100, 1, 101, 1);
